import { Job } from "@/types/job";

export const initialJobs: Job[] = [
  {
    id: "1",
    title: "Senior Frontend Developer",
    company: "WSO2",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "We are looking for a Senior Frontend Developer to join our dynamic team. You will be responsible for building user-facing features using modern web technologies.",
    requirements: ["React", "TypeScript", "Next.js", "5+ years experience"],
    salary: "LKR 200,000 - LKR 300,000",
    postedDate: "2024-01-15",
    applicationUrl: "https://example.com/apply/1",
  },
  {
    id: "2",
    title: "Backend Engineer",
    company: "Sysco Labs",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Join our backend team to build scalable APIs and microservices. Experience with cloud platforms and databases required.",
    requirements: [
      "Node.js",
      "Python",
      "AWS",
      "PostgreSQL",
      "3+ years experience",
    ],
    salary: "LKR 180,000 - LKR 250,000",
    postedDate: "2024-01-14",
    applicationUrl: "https://example.com/apply/2",
  },
  {
    id: "3",
    title: "UX Designer",
    company: "99X Technology",
    location: "Remote",
    jobType: "contract",
    description:
      "We need a talented UX Designer to help create intuitive and engaging user experiences for our digital products.",
    requirements: [
      "Figma",
      "User Research",
      "Prototyping",
      "2+ years experience",
    ],
    salary: "LKR 3,000 - LKR 5,000/hour",
    postedDate: "2024-01-13",
    applicationUrl: "https://example.com/apply/3",
  },
  {
    id: "4",
    title: "DevOps Engineer",
    company: "Virtusa",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Looking for a DevOps Engineer to manage our infrastructure and deployment pipelines. Strong automation skills required.",
    requirements: [
      "Docker",
      "Kubernetes",
      "CI/CD",
      "Terraform",
      "4+ years experience",
    ],
    salary: "LKR 220,000 - LKR 350,000",
    postedDate: "2024-01-12",
    applicationUrl: "https://example.com/apply/4",
  },
  {
    id: "5",
    title: "Product Manager",
    company: "IFS",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Seeking an experienced Product Manager to drive product strategy and work closely with engineering and design teams.",
    requirements: [
      "Product Strategy",
      "Agile",
      "Analytics",
      "3+ years experience",
    ],
    salary: "LKR 250,000 - LKR 400,000",
    postedDate: "2024-01-11",
    applicationUrl: "https://example.com/apply/5",
  },
  {
    id: "6",
    title: "Marketing Intern",
    company: "PickMe",
    location: "Colombo, Sri Lanka",
    jobType: "internship",
    description:
      "Great opportunity for a marketing student to gain hands-on experience in digital marketing and content creation.",
    requirements: [
      "Marketing fundamentals",
      "Social Media",
      "Content Creation",
    ],
    salary: "LKR 25,000/month",
    postedDate: "2024-01-10",
    applicationUrl: "https://example.com/apply/6",
  },
  {
    id: "7",
    title: "Mobile App Developer",
    company: "CodeGen International",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Join our mobile development team to create innovative mobile applications for iOS and Android platforms.",
    requirements: [
      "React Native",
      "Flutter",
      "Swift",
      "Kotlin",
      "2+ years experience",
    ],
    salary: "LKR 150,000 - LKR 250,000",
    postedDate: "2024-01-09",
    applicationUrl: "https://example.com/apply/7",
  },
  {
    id: "8",
    title: "Data Scientist",
    company: "MillenniumIT ESP",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "We are seeking a Data Scientist to analyze complex data sets and build machine learning models for our financial technology solutions.",
    requirements: [
      "Python",
      "Machine Learning",
      "SQL",
      "Statistics",
      "3+ years experience",
    ],
    salary: "LKR 200,000 - LKR 350,000",
    postedDate: "2024-01-08",
    applicationUrl: "https://example.com/apply/8",
  },
  {
    id: "9",
    title: "QA Engineer",
    company: "Zone24x7",
    location: "Kandy, Sri Lanka",
    jobType: "full-time",
    description:
      "Looking for a QA Engineer to ensure the quality of our software products through comprehensive testing strategies.",
    requirements: [
      "Selenium",
      "Jest",
      "Manual Testing",
      "API Testing",
      "2+ years experience",
    ],
    salary: "LKR 120,000 - LKR 200,000",
    postedDate: "2024-01-07",
    applicationUrl: "https://example.com/apply/9",
  },
  {
    id: "10",
    title: "Business Analyst",
    company: "John Keells IT",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Seeking a Business Analyst to bridge the gap between business stakeholders and technical teams in our digital transformation initiatives.",
    requirements: [
      "Business Analysis",
      "Agile",
      "Documentation",
      "Stakeholder Management",
      "3+ years experience",
    ],
    salary: "LKR 180,000 - LKR 280,000",
    postedDate: "2024-01-06",
    applicationUrl: "https://example.com/apply/10",
  },
  {
    id: "11",
    title: "Full Stack Developer",
    company: "hSenid Mobile Solutions",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Join our team to build end-to-end web applications. You'll work on both frontend and backend technologies.",
    requirements: [
      "React",
      "Node.js",
      "MongoDB",
      "REST APIs",
      "3+ years experience",
    ],
    salary: "LKR 170,000 - LKR 280,000",
    postedDate: "2024-01-05",
    applicationUrl: "https://example.com/apply/11",
  },
  {
    id: "12",
    title: "AI/ML Engineer",
    company: "Cambio Software Engineering",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Work on cutting-edge AI and machine learning projects. Build intelligent systems that solve real-world problems.",
    requirements: [
      "Python",
      "TensorFlow",
      "PyTorch",
      "Deep Learning",
      "4+ years experience",
    ],
    salary: "LKR 250,000 - LKR 400,000",
    postedDate: "2024-01-04",
    applicationUrl: "https://example.com/apply/12",
  },
  {
    id: "13",
    title: "Cybersecurity Analyst",
    company: "LSEG Technology",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Protect our systems and data from cyber threats. Monitor security incidents and implement security measures.",
    requirements: [
      "Network Security",
      "SIEM",
      "Penetration Testing",
      "ISO 27001",
      "3+ years experience",
    ],
    salary: "LKR 200,000 - LKR 320,000",
    postedDate: "2024-01-03",
    applicationUrl: "https://example.com/apply/13",
  },
  {
    id: "14",
    title: "UI/UX Designer",
    company: "Arimac",
    location: "Remote",
    jobType: "part-time",
    description:
      "Create beautiful and functional designs for web and mobile applications. Work with cross-functional teams.",
    requirements: [
      "Adobe XD",
      "Sketch",
      "User Testing",
      "Wireframing",
      "2+ years experience",
    ],
    salary: "LKR 2,500 - LKR 4,500/hour",
    postedDate: "2024-01-02",
    applicationUrl: "https://example.com/apply/14",
  },
  {
    id: "15",
    title: "Cloud Architect",
    company: "Dialog Axiata",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Design and implement cloud infrastructure solutions. Lead cloud migration and optimization projects.",
    requirements: [
      "AWS",
      "Azure",
      "Cloud Architecture",
      "Microservices",
      "6+ years experience",
    ],
    salary: "LKR 300,000 - LKR 500,000",
    postedDate: "2024-01-01",
    applicationUrl: "https://example.com/apply/15",
  },
  {
    id: "16",
    title: "Intern - Software Developer",
    company: "Pearson Lanka",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Start your career in software development with our supportive team. Learn from experienced developers.",
    requirements: [
      "Java",
      "JavaScript",
      "Git",
      "Problem Solving",
      "0-1 year experience",
    ],
    salary: "LKR 80,000 - LKR 120,000",
    postedDate: "2023-12-31",
    applicationUrl: "https://example.com/apply/16",
  },
  {
    id: "17",
    title: "Technical Writer",
    company: "Brandix IT",
    location: "Colombo, Sri Lanka",
    jobType: "contract",
    description:
      "Create comprehensive technical documentation for our software products and APIs.",
    requirements: [
      "Technical Writing",
      "API Documentation",
      "Markdown",
      "2+ years experience",
    ],
    salary: "LKR 2,000 - LKR 3,500/hour",
    postedDate: "2023-12-30",
    applicationUrl: "https://example.com/apply/17",
  },
  {
    id: "18",
    title: "Scrum Master",
    company: "London Stock Exchange Group",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Facilitate agile ceremonies and help teams deliver high-quality software efficiently.",
    requirements: [
      "Scrum",
      "Agile",
      "Jira",
      "Team Facilitation",
      "CSM Certified",
      "3+ years experience",
    ],
    salary: "LKR 190,000 - LKR 280,000",
    postedDate: "2023-12-29",
    applicationUrl: "https://example.com/apply/18",
  },
  {
    id: "19",
    title: "Game Developer",
    company: "Playhouse Games",
    location: "Remote",
    jobType: "full-time",
    description:
      "Build engaging mobile games using Unity. Create fun and addictive gaming experiences.",
    requirements: [
      "Unity",
      "C#",
      "Game Design",
      "3D Modeling",
      "2+ years experience",
    ],
    salary: "LKR 150,000 - LKR 250,000",
    postedDate: "2023-12-28",
    applicationUrl: "https://example.com/apply/19",
  },
  {
    id: "20",
    title: "IT Support Specialist",
    company: "Informatics International",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Provide technical support to end users. Troubleshoot hardware and software issues.",
    requirements: [
      "Windows",
      "Linux",
      "Networking",
      "Customer Service",
      "1+ year experience",
    ],
    salary: "LKR 60,000 - LKR 90,000",
    postedDate: "2023-12-27",
    applicationUrl: "https://example.com/apply/20",
  },
  {
    id: "21",
    title: "Blockchain Developer",
    company: "Akross Technologies",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Develop decentralized applications and smart contracts. Work with blockchain technologies.",
    requirements: [
      "Solidity",
      "Ethereum",
      "Web3.js",
      "Smart Contracts",
      "2+ years experience",
    ],
    salary: "LKR 220,000 - LKR 350,000",
    postedDate: "2023-12-26",
    applicationUrl: "https://example.com/apply/21",
  },
  {
    id: "22",
    title: "HR Coordinator",
    company: "Millennium IT",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Support HR operations including recruitment, onboarding, and employee relations.",
    requirements: [
      "HR Management",
      "Recruitment",
      "MS Office",
      "Communication",
      "1+ year experience",
    ],
    salary: "LKR 70,000 - LKR 110,000",
    postedDate: "2023-12-25",
    applicationUrl: "https://example.com/apply/22",
  },
  {
    id: "23",
    title: "Content Strategist",
    company: "LOVI",
    location: "Remote",
    jobType: "contract",
    description:
      "Develop content strategies for digital marketing campaigns. Create engaging content.",
    requirements: [
      "Content Strategy",
      "SEO",
      "Copywriting",
      "Analytics",
      "3+ years experience",
    ],
    salary: "LKR 2,800 - LKR 4,200/hour",
    postedDate: "2023-12-24",
    applicationUrl: "https://example.com/apply/23",
  },
  {
    id: "24",
    title: "Database Administrator",
    company: "Avaya",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Manage and maintain database systems. Ensure data integrity and optimal performance.",
    requirements: [
      "MySQL",
      "PostgreSQL",
      "Oracle",
      "Performance Tuning",
      "4+ years experience",
    ],
    salary: "LKR 180,000 - LKR 280,000",
    postedDate: "2023-12-23",
    applicationUrl: "https://example.com/apply/24",
  },
  {
    id: "25",
    title: "Network Engineer",
    company: "Etisalat Lanka",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Design and maintain network infrastructure. Troubleshoot network issues and optimize performance.",
    requirements: [
      "Cisco",
      "Network Security",
      "TCP/IP",
      "CCNA",
      "3+ years experience",
    ],
    salary: "LKR 160,000 - LKR 250,000",
    postedDate: "2023-12-22",
    applicationUrl: "https://example.com/apply/25",
  },
  {
    id: "26",
    title: "E-commerce Manager",
    company: "Daraz",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Manage e-commerce operations and drive online sales growth. Optimize customer experience.",
    requirements: [
      "E-commerce",
      "Analytics",
      "Marketing",
      "Project Management",
      "3+ years experience",
    ],
    salary: "LKR 200,000 - LKR 300,000",
    postedDate: "2023-12-21",
    applicationUrl: "https://example.com/apply/26",
  },
  {
    id: "27",
    title: "Software Engineering Intern",
    company: "Eyepax IT Consulting",
    location: "Colombo, Sri Lanka",
    jobType: "internship",
    description:
      "Learn software development in a professional environment. Work on real projects with guidance.",
    requirements: [
      "Basic Programming",
      "Problem Solving",
      "Eagerness to Learn",
    ],
    salary: "LKR 30,000/month",
    postedDate: "2023-12-20",
    applicationUrl: "https://example.com/apply/27",
  },
  {
    id: "28",
    title: "Sales Engineer",
    company: "Octave",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Combine technical knowledge with sales skills to help customers find the right solutions.",
    requirements: [
      "Technical Background",
      "Sales",
      "Communication",
      "Presentation Skills",
      "2+ years experience",
    ],
    salary: "LKR 120,000 - LKR 200,000 + Commission",
    postedDate: "2023-12-19",
    applicationUrl: "https://example.com/apply/28",
  },
  {
    id: "29",
    title: "React Native Developer",
    company: "Fortude",
    location: "Remote",
    jobType: "full-time",
    description:
      "Build cross-platform mobile applications using React Native. Create seamless user experiences.",
    requirements: [
      "React Native",
      "JavaScript",
      "Mobile Development",
      "Redux",
      "3+ years experience",
    ],
    salary: "LKR 180,000 - LKR 280,000",
    postedDate: "2023-12-18",
    applicationUrl: "https://example.com/apply/29",
  },
  {
    id: "30",
    title: "Site Reliability Engineer",
    company: "Wealthfirst Technology",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Ensure system reliability and scalability. Monitor performance and implement automation.",
    requirements: [
      "Linux",
      "Python",
      "Monitoring Tools",
      "Automation",
      "4+ years experience",
    ],
    salary: "LKR 230,000 - LKR 380,000",
    postedDate: "2023-12-17",
    applicationUrl: "https://example.com/apply/30",
  },
  {
    id: "31",
    title: "Video Editor",
    company: "Sri Lanka Telecom",
    location: "Colombo, Sri Lanka",
    jobType: "contract",
    description:
      "Edit and produce video content for marketing and promotional purposes.",
    requirements: [
      "Adobe Premiere Pro",
      "After Effects",
      "Video Editing",
      "2+ years experience",
    ],
    salary: "LKR 2,200 - LKR 3,800/hour",
    postedDate: "2023-12-16",
    applicationUrl: "https://example.com/apply/31",
  },
  {
    id: "32",
    title: "Python Developer",
    company: "Creative Software",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Develop backend services and APIs using Python. Work with data processing and automation.",
    requirements: [
      "Python",
      "Django",
      "Flask",
      "REST APIs",
      "3+ years experience",
    ],
    salary: "LKR 170,000 - LKR 270,000",
    postedDate: "2023-12-15",
    applicationUrl: "https://example.com/apply/32",
  },
  {
    id: "33",
    title: "Security Operations Analyst",
    company: "Accenture",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Monitor security events and respond to incidents. Implement security best practices.",
    requirements: [
      "Security Monitoring",
      "Incident Response",
      "SIEM",
      "Compliance",
      "2+ years experience",
    ],
    salary: "LKR 150,000 - LKR 240,000",
    postedDate: "2023-12-14",
    applicationUrl: "https://example.com/apply/33",
  },
  {
    id: "34",
    title: "Systems Analyst",
    company: "CMS Financial",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Analyze business requirements and design technical solutions. Work with stakeholders.",
    requirements: [
      "Systems Analysis",
      "SQL",
      "Business Process",
      "UML",
      "3+ years experience",
    ],
    salary: "LKR 160,000 - LKR 250,000",
    postedDate: "2023-12-13",
    applicationUrl: "https://example.com/apply/34",
  },
  {
    id: "35",
    title: "SEO Specialist",
    company: "DMS Electronics",
    location: "Remote",
    jobType: "part-time",
    description:
      "Optimize website content for search engines. Improve organic search rankings.",
    requirements: [
      "SEO",
      "Google Analytics",
      "Keyword Research",
      "Content Optimization",
      "2+ years experience",
    ],
    salary: "LKR 1,800 - LKR 3,200/hour",
    postedDate: "2023-12-12",
    applicationUrl: "https://example.com/apply/35",
  },
  {
    id: "36",
    title: "Java Developer",
    company: "Wiley Global",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Build enterprise applications using Java and Spring framework. Write clean, maintainable code.",
    requirements: [
      "Java",
      "Spring Boot",
      "Microservices",
      "MySQL",
      "4+ years experience",
    ],
    salary: "LKR 190,000 - LKR 300,000",
    postedDate: "2023-12-11",
    applicationUrl: "https://example.com/apply/36",
  },
  {
    id: "37",
    title: "Graphic Designer",
    company: "Unilever",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Create visual content for marketing campaigns and brand materials.",
    requirements: [
      "Adobe Creative Suite",
      "Graphic Design",
      "Branding",
      "Typography",
      "2+ years experience",
    ],
    salary: "LKR 90,000 - LKR 150,000",
    postedDate: "2023-12-10",
    applicationUrl: "https://example.com/apply/37",
  },
  {
    id: "38",
    title: "Financial Analyst",
    company: "Commercial Bank",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Analyze financial data and create reports. Support business decision-making.",
    requirements: [
      "Financial Analysis",
      "Excel",
      "Reporting",
      "Accounting",
      "2+ years experience",
    ],
    salary: "LKR 140,000 - LKR 220,000",
    postedDate: "2023-12-09",
    applicationUrl: "https://example.com/apply/38",
  },
  {
    id: "39",
    title: "IoT Engineer",
    company: "MAS Holdings",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Develop IoT solutions and connected devices. Work with sensors and embedded systems.",
    requirements: [
      "IoT Protocols",
      "Arduino",
      "Raspberry Pi",
      "C++",
      "3+ years experience",
    ],
    salary: "LKR 180,000 - LKR 280,000",
    postedDate: "2023-12-08",
    applicationUrl: "https://example.com/apply/39",
  },
  {
    id: "40",
    title: "Customer Success Manager",
    company: "Calcey Technologies",
    location: "Remote",
    jobType: "full-time",
    description:
      "Ensure customer satisfaction and retention. Build strong client relationships.",
    requirements: [
      "Customer Success",
      "Communication",
      "Problem Solving",
      "SaaS Experience",
      "2+ years experience",
    ],
    salary: "LKR 150,000 - LKR 240,000",
    postedDate: "2023-12-07",
    applicationUrl: "https://example.com/apply/40",
  },
  {
    id: "41",
    title: "Angular Developer",
    company: "Laugfs Holdings",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Build dynamic web applications using Angular framework. Implement responsive designs.",
    requirements: [
      "Angular",
      "TypeScript",
      "RxJS",
      "HTML/CSS",
      "3+ years experience",
    ],
    salary: "LKR 170,000 - LKR 270,000",
    postedDate: "2023-12-06",
    applicationUrl: "https://example.com/apply/41",
  },
  {
    id: "42",
    title: "Data Engineer",
    company: "Hemas Holdings",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Build and maintain data pipelines. Design data warehouse solutions.",
    requirements: [
      "Python",
      "SQL",
      "ETL",
      "Big Data",
      "Spark",
      "3+ years experience",
    ],
    salary: "LKR 200,000 - LKR 320,000",
    postedDate: "2023-12-05",
    applicationUrl: "https://example.com/apply/42",
  },
  {
    id: "43",
    title: "Project Coordinator",
    company: "Nations Trust Bank",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Coordinate project activities and support project managers. Track deliverables.",
    requirements: [
      "Project Management",
      "MS Office",
      "Communication",
      "Organization",
      "1+ year experience",
    ],
    salary: "LKR 80,000 - LKR 130,000",
    postedDate: "2023-12-04",
    applicationUrl: "https://example.com/apply/43",
  },
  {
    id: "44",
    title: "Automation Test Engineer",
    company: "Eurofins IT Solutions",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Design and implement automated testing frameworks. Ensure software quality.",
    requirements: [
      "Selenium",
      "Java",
      "TestNG",
      "CI/CD",
      "3+ years experience",
    ],
    salary: "LKR 160,000 - LKR 250,000",
    postedDate: "2023-12-03",
    applicationUrl: "https://example.com/apply/44",
  },
  {
    id: "45",
    title: "Social Media Manager",
    company: "Softlogic Holdings",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Manage social media presence across platforms. Create engaging content strategies.",
    requirements: [
      "Social Media Marketing",
      "Content Creation",
      "Analytics",
      "Copywriting",
      "2+ years experience",
    ],
    salary: "LKR 100,000 - LKR 160,000",
    postedDate: "2023-12-02",
    applicationUrl: "https://example.com/apply/45",
  },
  {
    id: "46",
    title: "Salesforce Developer",
    company: "Virtusa Polaris",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Customize and develop Salesforce applications. Implement CRM solutions.",
    requirements: [
      "Salesforce",
      "Apex",
      "Lightning",
      "Integration",
      "2+ years experience",
    ],
    salary: "LKR 180,000 - LKR 280,000",
    postedDate: "2023-12-01",
    applicationUrl: "https://example.com/apply/46",
  },
  {
    id: "47",
    title: "Business Intelligence Analyst",
    company: "Brandix",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Create dashboards and reports using BI tools. Analyze business data.",
    requirements: [
      "Power BI",
      "Tableau",
      "SQL",
      "Data Visualization",
      "2+ years experience",
    ],
    salary: "LKR 150,000 - LKR 240,000",
    postedDate: "2023-11-30",
    applicationUrl: "https://example.com/apply/47",
  },
  {
    id: "48",
    title: "Legal Assistant",
    company: "Aitken Spence",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Support legal team with documentation and research. Handle contract management.",
    requirements: [
      "Legal Knowledge",
      "Documentation",
      "Research",
      "MS Office",
      "1+ year experience",
    ],
    salary: "LKR 70,000 - LKR 110,000",
    postedDate: "2023-11-29",
    applicationUrl: "https://example.com/apply/48",
  },
  {
    id: "49",
    title: "SAP Consultant",
    company: "Hayleys",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Implement and customize SAP solutions. Provide technical support.",
    requirements: [
      "SAP",
      "ABAP",
      "Module Expertise",
      "Implementation",
      "4+ years experience",
    ],
    salary: "LKR 250,000 - LKR 400,000",
    postedDate: "2023-11-28",
    applicationUrl: "https://example.com/apply/49",
  },
  {
    id: "50",
    title: "Motion Graphics Designer",
    company: "MTV/MBC Networks",
    location: "Remote",
    jobType: "contract",
    description:
      "Create animated graphics and visual effects for broadcast and digital media.",
    requirements: [
      "After Effects",
      "Cinema 4D",
      "Motion Graphics",
      "3+ years experience",
    ],
    salary: "LKR 3,000 - LKR 5,000/hour",
    postedDate: "2023-11-27",
    applicationUrl: "https://example.com/apply/50",
  },
  {
    id: "51",
    title: "Platform Engineer",
    company: "Federated Tech",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Build and maintain platform infrastructure. Enable developer productivity.",
    requirements: [
      "Kubernetes",
      "Terraform",
      "CI/CD",
      "Cloud Platforms",
      "4+ years experience",
    ],
    salary: "LKR 220,000 - LKR 360,000",
    postedDate: "2023-11-26",
    applicationUrl: "https://example.com/apply/51",
  },
  {
    id: "52",
    title: "RPA Developer",
    company: "Ernst & Young",
    location: "Colombo, Sri Lanka",
    jobType: "full-time",
    description:
      "Develop robotic process automation solutions. Automate business processes.",
    requirements: [
      "UiPath",
      "Blue Prism",
      "Process Analysis",
      "VB.NET",
      "2+ years experience",
    ],
    salary: "LKR 160,000 - LKR 260,000",
    postedDate: "2023-11-25",
    applicationUrl: "https://example.com/apply/52",
  },
];
